# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nathan Arthur
email: narthur@tutanota.com
description: > # this means to ignore newlines until "baseurl:"
  "For the Lord hath redeemed Jacob, and ransomed him from the hand of him that was stronger than he" (Jeremiah 31:11).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.NathanArthur.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  narthur

# Build settings
markdown: kramdown
